# Generated by Django 6.0.1 on 2026-05-19 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Festival2026', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parque',
            name='horario',
        ),
        migrations.AddField(
            model_name='parque',
            name='horario_apertura',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Hora de apertura (HH:MM)'),
        ),
        migrations.AddField(
            model_name='parque',
            name='horario_cierre',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Hora de cierre (HH:MM)'),
        ),
    ]
