# Generated by Django 6.0.1 on 2026-05-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Festival2026', '0002_remove_parque_horario_parque_horario_apertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parque',
            name='tiene_danza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parque',
            name='tiene_musica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parque',
            name='tiene_teatro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parque',
            name='tiene_transporte',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parque',
            name='servicios',
            field=models.TextField(help_text='Lista de servicios adicionales disponibles'),
        ),
    ]
