# Generated by Django 6.0.1 on 2026-05-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Festival2026', '0003_parque_tiene_danza_parque_tiene_musica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parque',
            name='tiene_baños',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parque',
            name='tiene_cafeterias',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parque',
            name='tiene_guias',
            field=models.BooleanField(default=False),
        ),
    ]
