# Generated by Django 6.0.1 on 2026-05-19 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Festival2026', '0004_parque_tiene_baños_parque_tiene_cafeterias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parque',
            old_name='tiene_baños',
            new_name='tiene_banos',
        ),
    ]
