# Generated by Django 6.0.5 on 2026-05-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Festival2026', '0005_rename_tiene_baños_parque_tiene_banos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='parque',
            name='tiene_banos',
        ),
        migrations.RemoveField(
            model_name='parque',
            name='tiene_cafeterias',
        ),
        migrations.RemoveField(
            model_name='parque',
            name='tiene_danza',
        ),
        migrations.RemoveField(
            model_name='parque',
            name='tiene_guias',
        ),
        migrations.RemoveField(
            model_name='parque',
            name='tiene_musica',
        ),
        migrations.RemoveField(
            model_name='parque',
            name='tiene_teatro',
        ),
        migrations.RemoveField(
            model_name='parque',
            name='tiene_transporte',
        ),
        migrations.RemoveField(
            model_name='parque',
            name='servicios',
        ),
        migrations.AddField(
            model_name='parque',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='parques', to='Festival2026.servicio', verbose_name='Servicios adicionales'),
        ),
    ]
